[project]
name = "uv-project-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yee Hing Tong", email = "wild-endeavor@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flyte@git+https://github.com/flyteorg/flyte-sdk.git@7fb7d693c99ae44fc720ee78ad11ad533c5447de",
]

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
