[project]
name = "uv-project-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yee Hing Tong", email = "wild-endeavor@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flyte==2.0.0b29",
]

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"
